# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20170326_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='pending_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Public group'),
        ),
    ]
